start-line-location:
  ==: org.bukkit.Location
  world: mcr
  x: 10.0
  y: -59.0
  z: -6.0
  pitch: 0.0
  yaw: 0.0

end-line-location:
  ==: org.bukkit.Location
  world: world
  x: 10.0
  y: -59.0
  z: -507.0
  pitch: 0.0
  yaw: 0.0

end-line-direction: WEST
end-line-length: 21